rm(list = ls())
source("objects.R")
ce <- TSS.annotate.pipe(df = "bam_B6_noMismatch_scfilter.tsv", genome = "mm10",
                        just.ce = T)
saveRDS(ce, "ce.Rds")
# to the reader:
# required bam files (in bam_B6_noMismatch_scfilter.tsv)
# can be generated by following the scripts in analyses/nanoCAGE.
# also saving a copy of the R object for your convenience.

### loose filter
ce.loose <- peak.annotate.pipe(
  ce = ce, normalization = T, 
  genome = "mm10", work.dir = "verify/B6/loose_distclu/",
  tpm.threshold = 2, nrPassThreshold = 1, method = "distclu",  
  maxDist = 50, removeSingletons = T, keepSingletonsAbove = 4, 
  # minStability = 2, maxLength = 100, reduceToNonoverlapping = TRUE, 
  useMulticore = TRUE, nrCores = 4)
saveRDS(ce.loose, "ce.loose.Rds")
### strict filter
ce.strict <- peak.annotate.pipe(
  ce = ce, normalization = T,
  genome = "mm10", work.dir = "verify/B6/strict_distclu/",
  tpm.threshold = 2, nrPassThreshold = NULL, method = "distclu",  
  maxDist = 50, removeSingletons = T, keepSingletonsAbove = 4, 
  # minStability = 2, maxLength = 100, reduceToNonoverlapping = TRUE, 
  useMulticore = TRUE, nrCores = 4)
saveRDS(ce.strict, "ce.strict.Rds")

### use peaks detected in both loose and strict. 
# But the boundaries from loose are maintained
pass.2 <- plyranges::filter_by_overlaps(
  x = ce.loose@metadata$consensus_cap_0.7, 
  y = ce.strict@metadata$consensus_cap_0.7)

# add Ly49d promoters since it was filtered out by "strict".
gr.Klra4.TSS <- data.frame(chr = "chr6", start = c(130065215, 130067177), 
                           end = c(130065312, 130067333),
                           strand = "-") %>% makeGRangesFromDataFrame()
# these are not chosen randomly. They match the consensus peak positions in ce.loose perfectly

pass.2.gr <- pass.2
mcols(pass.2.gr) <- NULL
pass.2.klra4.gr <- c(pass.2.gr, gr.Klra4.TSS)
dir.create("verify/B6/pass2/")
saveRDS(pass.2.klra4.gr, "verify/B6/pass2/pass.2.klra4.gr.Rds")

cage.b6.se <- cager.get.counts(ce = ce.loose, gr = pass.2.klra4.gr, consensus = F, return.se = T)

saveRDS(cage.b6.se, "verify/B6/pass2/cage.b6.se.Rds")
