rm(list = ls())
source("objects.R")

sync.o.all <- readRDS("sync.o.all.Rds")

sync.o.all.rescue <- sync.o.rescue(
  sync.o = sync.o.all, regex.rescue = "Klra", rescue.col.name = "SYMBOL",
  bam.sample.map = "rescue.sample.map.tsv", bam.ext.size = 500, 
  rescue.shift = nkc.shift, tag = bamFanc::BOWTIE2.TAGS,
  header.file = "header.mm10", 
  m.score.cutoff = -0.1, threads = 6,
  rescue.report.dir = "rescue/report/")
saveRDS(sync.o.all.rescue, "rescue/sync.o.all.rescue.Rds")
# a copy of the result is offered.

# bam files listed in rescue.sample.map.tsv were generated by high sensitivity
# alignments (described in step1.3.1)
# the "ctrl" files are the output from AIAP. for a given Ly49 promoter, all reads
# mapped there by AIAP were counted.

# generate plots:
extrafont::loadfonts()
# you need to have Arial installed

p <- range.cor.2(sync.o = sync.o.all,
                 outfile = "rescue/rescue_pre_noCor.pdf",
                 use.template.2 = T,
                 add.cor = F)

p <- range.cor.2(sync.o = sync.o.all.rescue$sync.o.rescue, 
                 outfile = "rescue/rescue_post.pdf",
                 use.template.2 = T,
                 add.cor = F)
